name: backend_project
description: A sample command-line application.
version: 1.0.0


environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  shelf: ^1.3.0
  shelf_router: ^1.1.1


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
